version: '3.7'

services:
  zookeeper:
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    networks:
      - local
 
  kafka:
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    networks:
      - local

networks:
  local:
    name: $NETWORK